# Netlify build instructions
[build]
    command = "make -C docs/book build"
    publish = "docs/book/book"

# Standard Netlify redirects
[[redirects]]
    from = "https://master--cluster-api-aws.netlify.com/*"
    to = "https://master.cluster-api-aws.sigs.k8s.io/:splat"
    status = 301
    force = true

# HTTP-to-HTTPS rules
[[redirects]]
    from = "http://master.cluster-api-aws.sigs.k8s.io/*"
    to = "https://master.cluster-api-aws.sigs.k8s.io/:splat"
    status = 301
    force = true

[[redirects]]
    from = "http://master--cluster-api-aws.netlify.com/*"
    to = "http://master.cluster-api-aws.sigs.k8s.io/:splat"
    status = 301
    force = true
