commonLabels:
  cluster.x-k8s.io/v1alpha3: v1alpha3

# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/
resources:
- bases/infrastructure.cluster.x-k8s.io_awsmachines.yaml
- bases/infrastructure.cluster.x-k8s.io_awsclusters.yaml
- bases/infrastructure.cluster.x-k8s.io_awsfargateprofiles.yaml
- bases/infrastructure.cluster.x-k8s.io_awsmachinetemplates.yaml
- bases/infrastructure.cluster.x-k8s.io_awsmanagedclusters.yaml
- bases/infrastructure.cluster.x-k8s.io_awsmachinepools.yaml
- bases/infrastructure.cluster.x-k8s.io_awsmanagedmachinepools.yaml
- bases/infrastructure.cluster.x-k8s.io_awsclusterroleidentities.yaml
- bases/infrastructure.cluster.x-k8s.io_awsclusterstaticidentities.yaml
- bases/infrastructure.cluster.x-k8s.io_awsclustercontrolleridentities.yaml


# +kubebuilder:scaffold:crdkustomizeresource

patchesStrategicMerge:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
- patches/webhook_in_awsmachines.yaml
- patches/webhook_in_awsclusters.yaml
- patches/webhook_in_awsmachinetemplates.yaml
- patches/webhook_in_awsclustercontrolleridentities.yaml
- patches/webhook_in_awsclusterroleidentities.yaml

  # +kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable webhook, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
- patches/cainjection_in_awsmachines.yaml
- patches/cainjection_in_awsclusters.yaml
- patches/cainjection_in_awsmachinetemplates.yaml
- patches/cainjection_in_awsclustercontrolleridentities.yaml
- patches/cainjection_in_awsclusterroleidentities.yaml

# +kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
