namePrefix: capa-eks-control-plane-

commonLabels:
  cluster.x-k8s.io/provider: "control-plane-eks"

bases:
- crd
- default
- webhook

patchesJson6902:
- target:
    group: apiextensions.k8s.io
    version: v1
    kind: CustomResourceDefinition
    name: awsmanagedcontrolplanes.controlplane.cluster.x-k8s.io
  path: patch_crd_webhook_namespace.yaml